language: python
python:
  - "3.6"
after_success: coveralls

install:
  - pip install -r requirements.txt

script:
  - python3 -m unittest discover -p "*_test.py"

notifications:
  email:
    recipients:
      - monadv@yandex.ru
    on_success: always
    on_failure: always