language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

script:
  - pytest

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - monadv@yandex.ru
    on_success: always
    on_failure: always