# Site settings
title: LDSS Tensor Structures | Scientific blog
description: "A minimal blog template, build with Jekyll."
url: "https://demid5111.github.io/ldss-tensor-structures-docs/"
author:
  name: "Alexander Demidovskij"
  email: "monadv@yandex.ru"
  url: "http://www.hse.ru/staff/demidovs"

# Build settings
baseurl: /ldss-tensor-structures-docs/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "0.0.1"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
